// MD linter
{
"default": true,
"MD047": false,
"MD012": false,
"MD003": false,
"MD007": false,
"MD013": false,
"MD022": false,
"MD025": false,
"MD032": false,
"MD034": false,
"MD033": false,
"MD036": false,
"MD000": false,
"MD000": false,
"no-hard-tabs": false,
"markdownlint.focusmode": true,
"markdownlint.run": "onSave"
}